FROM ubuntu:latest
MAINTAINER ZhihongLi <zhihongli@bennington.edu>

RUN apt-get update && apt-get install -y \
	curl \
	python-dev \
	python-setuptools \
	python3-pip \
	--no-install-recommends && \
	rm -rf /var/lib/apt/lists/* && \
	apt-get clean

RUN pip3 install --upgrade pip
RUN pip3 install flask
RUN pip3 install requests

ADD . /master
WORKDIR /master

EXPOSE 5000

ENV FLASK_APP=main.py

CMD python3 /usr/local/bin/flask run --host=0.0.0.0

